apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote-back
  template:
    metadata:
      labels:
        app: vote-back
    spec:
      nodeSelector:
        beta.kubernetes.io/os: linux
      containers:
        - name: vote-back
          image: redis:latest
          env:
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
          ports:
            - containerPort: 6379
              name: redis
          resources:
            requests:
              cpu: 250m
            limits:
              cpu: 500m
              memory: 500M
---
apiVersion: v1
kind: Service
metadata:
  name: vote-back
spec:
  ports:
    - port: 6379
  selector:
    app: vote-back
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote-front
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: vote-front
    spec:
      nodeSelector:
        beta.kubernetes.io/os: linux
      containers:
        - name: vote-front
          image: ghcr.io/rahulrai-in/azure-voting-app-dotnet:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 250m
            limits:
              cpu: 500m
              memory: 500M
          env:
            - name: ConnectionStrings__RedisHost
              value: "vote-back"
---
apiVersion: v1
kind: Service
metadata:
  name: vote-front
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: vote-front
